#include <array>
#include <string>
#include <vector>
#include "strUtil.hpp"

namespace Uranium::ItemGroups
{
	static const std::vector<std::string> ItemGroupNames = {
		"itemGroup.name.planks",
		"itemGroup.name.walls",
		"itemGroup.name.fence",
		"itemGroup.name.fenceGate",
		"itemGroup.name.stairs",
		"itemGroup.name.door",
		"itemGroup.name.trapdoor",
		"itemGroup.name.element",
		"itemGroup.name.glass",
		"itemGroup.name.glassPane",
		"itemGroup.name.slab",
		"itemGroup.name.stoneBrick",
		"itemGroup.name.sandstone",
		"itemGroup.name.copper",
		"itemGroup.name.wool",
		"itemGroup.name.woolCarpet",
		"itemGroup.name.concretePowder",
		"itemGroup.name.concrete",
		"itemGroup.name.stainedClay",
		"itemGroup.name.glazedTerracotta",
		"itemGroup.name.ore",
		"itemGroup.name.stone",
		"itemGroup.name.log",
		"itemGroup.name.wood",
		"itemGroup.name.leaves",
		"itemGroup.name.sapling",
		"itemGroup.name.seed",
		"itemGroup.name.crop",
		"itemGroup.name.grass",
		"itemGroup.name.coral_decorations",
		"itemGroup.name.flower",
		"itemGroup.name.dye",
		"itemGroup.name.rawFood",
		"itemGroup.name.mushroom",
		"itemGroup.name.monsterStoneEgg",
		"itemGroup.name.mobEgg",
		"itemGroup.name.coral",
		"itemGroup.name.sculk",
		"itemGroup.name.helmet",
		"itemGroup.name.chestplate",
		"itemGroup.name.leggings",
		"itemGroup.name.boots",
		"itemGroup.name.sword",
		"itemGroup.name.axe",
		"itemGroup.name.pickaxe",
		"itemGroup.name.shovel",
		"itemGroup.name.hoe",
		"itemGroup.name.arrow",
		"itemGroup.name.cookedFood",
		"itemGroup.name.miscFood",
		"itemGroup.name.goatHorn",
		"itemGroup.name.horseArmor",
		"itemGroup.name.potion",
		"itemGroup.name.splashPotion",
		"itemGroup.name.lingeringPotion",
		"itemGroup.name.bed",
		"itemGroup.name.candles",
		"itemGroup.name.chemistrytable",
		"itemGroup.name.anvil",
		"itemGroup.name.chest",
		"itemGroup.name.shulkerBox",
		"itemGroup.name.record",
		"itemGroup.name.sign",
		"itemGroup.name.hanging_sign",
		"itemGroup.name.skull",
		"itemGroup.name.enchantedBook",
		"itemGroup.name.boat",
		"itemGroup.name.chestboat",
		"itemGroup.name.rail",
		"itemGroup.name.minecart",
		"itemGroup.name.buttons",
		"itemGroup.name.pressurePlate",
		"itemGroup.name.banner",
		"itemGroup.name.banner_pattern",
		"itemGroup.name.potterySherds",
		"itemGroup.name.smithing_templates",
		"itemGroup.name.firework",
		"itemGroup.name.fireworkStars",
		"itemGroup.name.dirt",
		"itemGroup.name.cobblestone",
		"itemGroup.name.natureBuildingBlocks",
		"itemGroup.name.sand",
		"itemGroup.name.gravel",
		"itemGroup.name.oreBlocks",
		"itemGroup.name.redstoneContainers",
		"itemGroup.name.musicBlocks",
		"itemGroup.name.pistons",
		"itemGroup.name.natureMisc",
		"itemGroup.name.greenery",
		"itemGroup.name.brick",
		"itemGroup.name.tnt",
		"itemGroup.name.enchantingTable",
		"itemGroup.name.constructionMisc",
		"itemGroup.name.torch",
		"itemGroup.name.craftingTables",
		"itemGroup.name.furnaces",
		"itemGroup.name.climbing",
		"itemGroup.name.redstoneProducers",
		"itemGroup.name.redstone",
		"itemGroup.name.ice",
		"itemGroup.name.cactus",
		"itemGroup.name.clay",
		"itemGroup.name.glowstone",
		"itemGroup.name.pumpkins",
		"itemGroup.name.ironFence",
		"itemGroup.name.beacon",
		"itemGroup.name.endPortalFrame",
		"itemGroup.name.eggBlocks",
		"itemGroup.name.lights",
		"itemGroup.name.purpur",
		"itemGroup.name.endRod",
		"itemGroup.name.permission",
		"itemGroup.name.camera",
		"itemGroup.name.lectern",
		"itemGroup.name.grindStone",
		"itemGroup.name.bell",
		"itemGroup.name.composter",
		"itemGroup.name.chiseledBookshelf"
	};
	enum class ItemGroup : unsigned char 
	{
		planks = 0,
		walls = 1,
		fence = 2,
		fenceGate = 3,
		stairs = 4,
		door = 5,
		trapdoor = 6,
		element = 7,
		glass = 8,
		glassPane = 9,
		slab = 10,
		stoneBrick = 11,
		sandstone = 12,
		copper = 13,
		wool = 14,
		woolCarpet = 15,
		concretePowder = 16,
		concrete = 17,
		stainedClay = 18,
		glazedTerracotta = 19,
		ore = 20,
		stone = 21,
		log = 22,
		wood = 23,
		leaves = 24,
		sapling = 25,
		seed = 26,
		crop = 27,
		grass = 28,
		coral_decorations = 29,
		flower = 30,
		dye = 31,
		rawFood = 32,
		mushroom = 33,
		monsterStoneEgg = 34,
		mobEgg = 35,
		coral = 36,
		sculk = 37,
		helmet = 38,
		chestplate = 39,
		leggings = 40,
		boots = 41,
		sword = 42,
		axe = 43,
		pickaxe = 44,
		shovel = 45,
		hoe = 46,
		arrow = 47,
		cookedFood = 48,
		miscFood = 49,
		goatHorn = 50,
		horseArmor = 51,
		potion = 52,
		splashPotion = 53,
		lingeringPotion = 54,
		bed = 55,
		candles = 56,
		chemistrytable = 57,
		anvil = 58,
		chest = 59,
		shulkerBox = 60,
		record = 61,
		sign = 62,
		hanging_sign = 63,
		skull = 64,
		enchantedBook = 65,
		boat = 66,
		chestboat = 67,
		rail = 68,
		minecart = 69,
		buttons = 70,
        pressurePlate = 71,
		banner = 72,
		banner_pattern = 73,
		potterySherds = 74,
		smithing_templates = 75,
		firework = 76,
		fireworkStars = 77,
		dirt = 78,
		cobblestone = 79,
		natureBuildingBlocks = 80,
		sand = 81,
		gravel = 82,
		oreBlocks = 83,
		redstoneContainers = 84,
		musicBlocks = 85,
		pistons = 86,
		natureMisc = 87,
		greenery = 88,
		brick = 89,
		tnt = 90,
		enchantingTable = 91,
		constructionMisc = 92,
		torch = 93,
		craftingTables = 94,
		furnaces = 95,
		climbing = 96,
		redstoneProducers = 97,
		redstone = 98,
		ice = 99,
		cactus = 100,
		clay = 101,
		glowstone = 102,
		pumpkins = 103,
		ironFence = 104,
		beacon = 105,
		endPortalFrame = 106,
		eggBlocks = 107,
		lights = 108,
		purpur = 109,
		endRod = 110,
		permission = 111,
		camera = 112,
		lectern = 113,
		grindStone = 114,
		bell = 115,
		composter = 116,
		chiseledBookshelf = 117,
		CUSTOM = 118, // This theorectically should never be used, but it is here just in case. i ever stop working on this project and someone else is using it.
		NUL = 119 // This is used for when the item group is not set.
	};
	static CStrWithLength itemGroupToString(ItemGroup itemGroup)
	{
		return { ItemGroupNames[static_cast<int>(itemGroup)].c_str(), ItemGroupNames[static_cast<int>(itemGroup)].size() };
	}
}
        
    